config/routes.rb
Vorfreude::Application.routes.draw do
  get "p/trending"
  resources :cds

  root :to => redirect('/cds')

end

app/models/cd.rb
class Cd < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  include InferredSlug::Slug

  validates :title, presence: true, length: { minimum:4 }
  validates_datetime :time, :after => :now

  def slug
    "#{id}/#{title}"
  end

  def to_param
    normalized_title = title.gsub(' ', '-').gsub(/[^a-zA-Z0-9\_\-\.]/, '')
    "#{self.id}-#{normalized_title}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/p_controller.rb
class PController < ActionController::Base
  def trending
    @cds = Cd.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/p_helper.rb
module PHelper
end

app/views/cds/_form.html.erb
<%= form_for @cd, :html => {:multipart => true, :class => 'form'} do |f| %>
  <% if @cd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cd.errors.count, "error") %> prohibited this cd from being saved:</h2>

      <ul>
      <% @cd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form role="form">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control", :placeholder => "What are you looking forward to?" %>
  </div>

  <div class="form-group">
    <%= f.label :link %><br/>
    <%= f.text_field :link, :class => "form-control", :placeholder => "Link to more information goes here!" %>
  </div>

  <div class="form-group">
    <%= f.label :time %><br/>
    <%= f.datetime_select :time, order: [:day, :month, :year], :minute_step => 5, :class => 'dropdown-menu' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit 'Start counting', :class => 'btn btn-success btn-lg col-md-12' %>
  </form>
<% end %>

app/views/cds/edit.html.erb
<h1>Editing cd</h1>

<%= render 'form' %>

<%= link_to 'Show', @cd %> |
<%= link_to 'Back', cds_path %>

app/views/cds/index.html.erb
<div class="col-md-10 col-md-offset-1">

<h1>Vorfreude index</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Time</th>
      <th>Image</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cds.each do |cd| %>
      <tr>
        <td><%= cd.title %></td>
        <td><%= cd.time %></td>
        <td><%= link_to image_tag(cd.image_url, :height => 30), cd.image_url %></td>
        <td><%= cd.link %></td>
        <td><%= link_to 'Show', cd %></td>
        <td><%= link_to 'Edit', edit_cd_path(cd) %></td>
        <td><%= button_to 'Destroy', cd, :method => :delete, :class => 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Countdown', new_cd_path, :class => 'btn btn-success btn-lg' %>

</div>

app/views/cds/new.html.erb
<h1>New cd</h1>

<%= render 'form' %>

<%= link_to 'Back', cds_path %>

app/views/cds/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :pagetitle do %>
	"<%= @cd.title %>" – on Vorfreude.to
<% end %>

<% content_for :title do %>
  <%= @cd.title %>
<% end %>

<% content_for :time do %>
  <script type='text/javascript'>

		var count = '<%= @cd.time.to_i %>';

		var created_at = '<%= @cd.created_at.to_i %>';
		var now = Math.round(new Date().getTime() / 1000);
		var days, hours, minutes, seconds, tmp, width;

		var timer = $.timer(
			function() {
				tmp = count-now;
				width = (now-created_at)/(count-created_at)*100;

				if(tmp <=0 ) {
					$('.count').html('This event is over.');
					$('.progress-bar').attr('style', 'width:100%');
					$('.progress-bar').attr('aria-valuenow', 100);
				}
				else {
					seconds = tmp % 60;
					if (seconds < 10) {
						seconds = '0'+seconds;
					}
					minutes = Math.floor(tmp/60) % 60;
					if (minutes < 10) {
						minutes = '0'+minutes;
					}
					hours 	= Math.floor(tmp/60/60) % 24;
					if (hours < 10) {
						hours = '0'+hours;
					}
					days		= Math.floor(tmp/60/60/24);
					if (days < 10) {
						days = '0'+days;
					}

					$('.count').html(days+':'+hours+':'+minutes+':'+seconds);
					$('.progress-bar').attr('style', 'width:' + Math.round(width) + '%');
					$('.progress-bar').attr('aria-valuenow', Math.round(width));
				}
				count--;
			}, 1000, true
		);
		
		if($('.count').is(':empty')) {
			
			
		}
		
		else {
			
		  	$('#countdown').delay(1000).fadeIn('slow', function () {
		     	$('#title').animate({'opacity': 'show', 'paddingTop': 0}, 1000);
			 	$('#time').animate({'opacity': 'show'}, 1000);
				$('#bar').animate({'opacity': 'show'}, 2000);
		  	});
		}

  </script>
<% end %>

<% content_for :image do %>
	<style type="text/css" media="screen">
		.site-wrapper {
  		background: url('<%= @cd.image_url if @cd.image? %>') no-repeat top center;
			background-size: 110% auto;
		}
	</style>
<% end %>

<% content_for :link do %>
	<% if @cd.link? %>
		<%= link_to 'Details', @cd.link, :class => 'btn btn-default btn-xs' %>
	<% end %>
<% end %>

<% content_for :url do %>
	<%= cd_url %>
<% end %>

<% content_for :image_url do %>
	<%= @cd.image_url %>
<% end %>

<p>
  <strong>Image:</strong>
  <%= image_tag(@cd.image_url, :width => 600) if @cd.image.present? %>
</p>

<p>
  <strong>Link:</strong>
  <%= @cd.link %>
</p>

<%= link_to 'Edit', edit_cd_path(@cd) %> |
<%= link_to 'Back', cds_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Vorfreude</title>

  <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap-theme.min.css" type="text/css" media="screen">
  <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap.min.css" type="text/css" media="screen">

  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.min.js" type="text/javascript"></script>
  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.timer.js" type="text/javascript"></script>
  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/docs.min.js" type="text/javascript"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :pagetitle %></title>

  <meta property="og:title" content="<%= yield :pagetitle %>">
  <meta property="og:type" content="activity">
  <meta property="og:url" content="<%= yield :url %>">
  <meta property="og:image" content="<%= yield :image_url %>">
  <meta property="og:site_name" content="Vorfreude">
  <meta property="og:description" content="I'm looking forward to <%= yield :title %> - let's share the Vorfreude. And see you there.">

  <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap-theme.min.css" type="text/css" media="screen">
  <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap.min.css" type="text/css" media="screen">
  <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/cover.css" type="text/css" media="screen">
  <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/ss-social-regular.css" type="text/css" media="screen">

  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.min.js" type="text/javascript"></script>
  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.timer.js" type="text/javascript"></script>
  <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/docs.min.js" type="text/javascript"></script>

  <%= yield :image %>

</head>

<body style="">

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Vorfreude</h3>
              <ul class="nav masthead-nav">
                <li><%= link_to 'Share your Vorfreude', new_cd_path %></li>
                <li><%= link_to 'Trending', p_trending_path %></li>
              </ul>
            </div>
          </div>

          <div class="inner cover" id="countdown">
            <h1 class="cover-heading" id="title" style="padding-top:150px; display:none"><%= yield :title %><%= yield :link %></h1>

            <div class="progress" style="height: 5px; display:none" id="bar">
              <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                <span class="sr-only"></span>
              </div>
            </div>

            <h2 class="count" id="time" style="display:none"><%= yield :time %></h2>
          </div>

          <div class="mastfoot">
            <div id="share">
              <a class="social" href="https://www.facebook.com/sharer/sharer.php?u=<%= yield :url %>"><i class="ss-icon ss-facebook"></i></a>
              <a class="social" href="http://twitter.com/home?status=I'm looking forward to '<%= yield :title %>' <%= yield :url %> #vorfreude"><i class="ss-icon ss-twitter"></i></a>
              <a class="social" href="https://plus.google.com/share?url=<%= yield :url %>"><i class="ss-icon ss-googleplus"></i></a>
            </div>

            <div class="inner">
              <p>Made with excitement by <a href="https://twitter.com/mikekotsch">@mikekotsch</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

</body>
</html>

app/views/layouts/new.html.erb
<!DOCTYPE html>

<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>Make your own countdown – on Vorfreude.to</title>

    <meta property="og:title" content="Share your Vorfreude">
    <meta property="og:type" content="activity">
    <meta property="og:url" content="http://vorfreude.mikekotsch.de">
    <meta property="og:image" content="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/t1/p320x320/1613776_10152267307180649_1964006563_n.jpg">
    <meta property="og:site_name" content="Vorfreude">
    <meta property="og:description" content="I'm looking forward to NAME - let's share the Vorfreude. And see you there.">

    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap-theme.min.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap.min.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/cover.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/ss-social-regular.css" type="text/css" media="screen">

    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.min.js" type="text/javascript"></script>
    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.timer.js" type="text/javascript"></script>
    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/docs.min.js" type="text/javascript"></script>

    <style type="text/css" media="screen">
      select {
        color:black;
      }
    </style>

</head>

  <body>

    <div class="site-wrapper new-countdown">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Vorfreude</h3>
              <ul class="nav masthead-nav">
                <li class="active"><%= link_to 'Share your Vorfreude', new_cd_path %></li>
                <li><%= link_to 'Trending', p_trending_path %></li>
              </ul>
            </div>
          </div>

          <div class="inner cover text-left col-md-8 col-md-offset-2">
            <h1 class="cover-heading text-center">Share your Vorfreude</h1>
            <%= render 'form' %>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Made with excitement by <a href="https://twitter.com/mikekotsch">@mikekotsch</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

</body>
</html>

app/views/p/trending.html.erb
<!DOCTYPE html>

<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>Trending Vorfreude</title>

    <meta property="og:title" content="Trending Vorfreude">
    <meta property="og:type" content="activity">
    <meta property="og:url" content="http://vorfreude.mikekotsch.de">
    <meta property="og:image" content="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/t1/p320x320/1613776_10152267307180649_1964006563_n.jpg">
    <meta property="og:site_name" content="Vorfreude">
    <meta property="og:description" content="I'm looking forward to NAME - let's share the Vorfreude. And see you there.">

    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap-theme.min.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/bootstrap.min.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/cover.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://assets-mkotsch.s3.amazonaws.com/vorfreude/css/ss-social-regular.css" type="text/css" media="screen">

    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.min.js" type="text/javascript"></script>
    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/jquery.timer.js" type="text/javascript"></script>
    <script src="https://assets-mkotsch.s3.amazonaws.com/vorfreude/js/docs.min.js" type="text/javascript"></script>

</head>

  <body>

    <div class="site-wrapper new-countdown">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Vorfreude</h3>
              <ul class="nav masthead-nav">
                <li><%= link_to 'Share your Vorfreude', new_cd_path %></li>
                <li class="active"><%= link_to 'Trending', p_trending_path %></li>
              </ul>
            </div>
          </div>

          <div class="inner cover text-left">
            <h1 class="cover-heading text-center" style="padding-bottom: 25px;">Trending Vorfreude</h1>
            <div class="row">
              <div class="col-md-3 col-md-offset-1 text-center">
                <a href="http://i.imgur.com/OXBQcPa.gif">
                  <img src="http://i.imgur.com/OXBQcPa.gif" alt="" class="img-circle" style="width:100%; border: 3px solid white">
                  <h3>Come the fuck on!</h3>
                </a>
              </div>
              <div class="col-md-3 col-md-offset-1 text-center">
                <a href="http://i.imgur.com/OXBQcPa.gif">
                  <img src="http://i.imgur.com/OXBQcPa.gif" alt="" class="img-circle" style="width:100%; border: 3px solid white">
                  <h3>Come the fuck on!</h3>
                </a>
              </div>
              <div class="col-md-3 col-md-offset-1 text-center">
                <a href="http://i.imgur.com/OXBQcPa.gif">
                  <img src="http://i.imgur.com/OXBQcPa.gif" alt="" class="img-circle" style="width:100%; border: 3px solid white">
                  <h3>Come the fuck on!</h3>
                </a>
              </div>
            </div>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Made with excitement by <a href="https://twitter.com/mikekotsch">@mikekotsch</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

</body>
</html>